# Configuration file for TEs-Analyser #

#file containing the sample information
samples: configuration/samples.tsv
#file containing the sample paths to raw data
fastq_files: configuration/fastq_files.tsv

#whether perform trimming or not
trimming: false

#parameters for the tools used:

params:
  fastp:
    se: "-t 1 -A -Q -L"
    pe: "-t 1 -A -Q -L" 
  star_first_pass: "--outSAMunmapped Within --outFilterType BySJout --outFilterMultimapNmax 30 --outFilterMismatchNmax 999" 



diffexp:
  # Filter thresholds to call differentially expressed genes
  pval: 0.05
  log2fc: 1.5
  # contrasts for the deseq2 results method
  contrasts:
    Control-vs-Treatment:
      - Control
      - Treatment

tools_cpu:
  fastp_pe: 5
  fastp_se: 5
  STAR_first_pass: 10
  STAR_second_pass: 10


