# Configuration file for TEs-Analyser #

#file containing the sample information
samples: configuration/samples.tsv
#file containing the sample paths to raw data
fastq_files: configuration/fastq_files.tsv

#whether perform trimming or not
trimming: false

#parameters for the tools used:

params:
  fastp:
    se: "-t 1 -A -Q -L"
    pe: "-t 1 -A -Q -L" 
  star_first_pass: "--outSAMunmapped Within --outFilterType BySJout --outFilterMultimapNmax 100 --outFilterMismatchNmax 999 --outMultimappedOrder Random" 
  star_second_pass: "--outFilterMultimapNmax 30 --outFilterMismatchNmax 999 --outMultimappedOrder Random"

  #HTseqcount outputs 3 columns per sample. 
  #col 1: unstranded
  #col 2: first read of a pair has to map to the same strand as the gene, and the second read has to map on the opposite strand 
  #col 3: reverse of line above

  htseq_count_column: 3
  
  drop_seq_strand: false    #whether to use strand info for tagging the bam files or not.

  #script with the filtering options for removing reads mapping on coding genes
  bam_filtering_json: "./workflow/scripts/filtering_settings_TEs.json"
  
  summariseOverlap: 
  
  bamCoverage: "-bs 1 --normalizeUsing CPM"  #bin size of 1
  

# input files required by the pipeline:
ref:
  genome: "human" #"mouse"
  genome_index: "/shares/CIBIO-Storage/CIBIO/sharedLC/human_genome/human_star_index"   #"/shares/CIBIO-Storage/CIBIO/sharedLC/mouse_genome/mouse_reference_files_GRCm38_p6"
  pseudo_genome_index: "/shares/CIBIO-Storage/GROUPS/sharedLC/Davide/TE_pseudo_genome/TE_pseudogenome_human_hg38/STAR_index_TE_pseudogenome_human" #"/shares/CIBIO-Storage/GROUPS/sharedLC/Davide/TE_pseudo_genome/STAR_index_TE_pseudogenome"

  gtf_file: "/shares/CIBIO-Storage/CIBIO/sharedLC/human_genome/gencode.v36.annotation.GRCh38.p13.gtf" #"/shares/CIBIO-Storage/CIBIO/sharedLC/mouse_genome/gencode.vM25.annotation.gtf"
  gtf_file_TEs: "/shares/CIBIO-Storage/GROUPS/sharedLC/Davide/TE_pseudo_genome/TE_pseudogenome_human_hg38/new_hg38_TE_pseudo_gtf.gtf"  #"/shares/CIBIO-Storage/GROUPS/sharedLC/Davide/TE_pseudo_genome/new_TE_gtf_file.gtf"

dropseq_jar: "/home/davide.bressan-1/tools/Drop-seq_tools-2.4.0/jar/dropseq.jar"

#parameters for the differential expression analysis. you can set multiple contrasts and/or multple thresholds

diffexp:
  # Filter thresholds to call differentially expressed genes
  pval: 
    - 0.05
  log2FC: 
    - 1.5
  # contrasts for the deseq2 results method
  contrasts:
    A1AKO-vs-A1AWT:
      - A1AKO
      - A1AWT
    TP53arid1aDKO-vs-TP53KO:
      - TP53arid1aDKO
      - TP53KO
# for each tool set the number of threads

tools_cpu:
  fastp_pe: 5
  fastp_se: 5
  STAR_first_pass: 5 #10
  STAR_second_pass: 5 #10
  samtools_sort: 5
  bamCoverage: 5


